// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCESkYi0j7BdkK49xwwtyKK2XJvODmc1VM',
    appId: '1:1000010005213:web:1d75ea2cb1e764dc783934',
    messagingSenderId: '1000010005213',
    projectId: 'edupro-b2b9d',
    authDomain: 'edupro-b2b9d.firebaseapp.com',
    storageBucket: 'edupro-b2b9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFIWiTbebWVAhJgoSaSHmF13qK9o4Bs9I',
    appId: '1:1000010005213:android:25aa05f81e19d642783934',
    messagingSenderId: '1000010005213',
    projectId: 'edupro-b2b9d',
    storageBucket: 'edupro-b2b9d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGM6RzT0EQNpeoHeyyumncc95DGcgFWHw',
    appId: '1:1000010005213:ios:fd3cfdf0df05c057783934',
    messagingSenderId: '1000010005213',
    projectId: 'edupro-b2b9d',
    storageBucket: 'edupro-b2b9d.firebasestorage.app',
    iosBundleId: 'com.example.eduproMobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGM6RzT0EQNpeoHeyyumncc95DGcgFWHw',
    appId: '1:1000010005213:ios:fd3cfdf0df05c057783934',
    messagingSenderId: '1000010005213',
    projectId: 'edupro-b2b9d',
    storageBucket: 'edupro-b2b9d.firebasestorage.app',
    iosBundleId: 'com.example.eduproMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCESkYi0j7BdkK49xwwtyKK2XJvODmc1VM',
    appId: '1:1000010005213:web:965e9c9262e28c02783934',
    messagingSenderId: '1000010005213',
    projectId: 'edupro-b2b9d',
    authDomain: 'edupro-b2b9d.firebaseapp.com',
    storageBucket: 'edupro-b2b9d.firebasestorage.app',
  );
}
